export const categories = [
  { type: "fruit", color: "orange", src: "fa-solid fa-apple-whole" },
  { type: "vegetable", color: "green", src: "fa-solid fa-carrot" },
  { type: "meat", color: "red", src: "fa-solid fa-drumstick-bite" },
  { type: "dairy", color: "blue", src: "fa-solid fa-cheese" },
  { type: "grain", color: "yellow", src: "fa-solid fa-bread-slice" },
  { type: "snacks", color: "brown", src: "fa-solid fa-cubes-stacked" },
  { type: "sweets", color: "lightpink", src: "fa-solid fa-ice-cream" },
  { type: "frozen", color: "lightblue", src: "fa-solid fa-jar" },
  { type: "misc foods", color: "gray", src: "fa-solid fa-jar" },
  { type: "other", color: "gray", src: "fa-solid fa-jar" },
];

export const items = [
  { name: "apples", type: "fruit", total: 0, notes: "", checked: false },
  {
    name: "broccoli",
    type: "vegetable",
    total: 0,
    notes: "",
    checked: false,
  },
  { name: "chicken", type: "meat", total: 0, notes: "", checked: false },
  { name: "beef", type: "meat", total: 0, notes: "", checked: false },
  { name: "turkey", type: "meat", total: 0, notes: "", checked: false },
  { name: "pork", type: "meat", total: 0, notes: "", checked: false },
  { name: "fish", type: "meat", total: 0, notes: "", checked: false },
  { name: "milk", type: "dairy", total: 0, notes: "", checked: false },
  { name: "bananas", type: "fruit", total: 0, notes: "", checked: false },
  { name: "pears", type: "fruit", total: 0, notes: "", checked: false },
  { name: "grapes", type: "fruit", total: 0, notes: "", checked: false },
  { name: "raspberries", type: "fruit", total: 0, notes: "", checked: false },
  {
    name: "blackberries",
    type: "fruit",
    total: 0,
    notes: "",
    checked: false,
  },
  { name: "blueberries", type: "fruit", total: 0, notes: "", checked: false },
  { name: "oranges", type: "fruit", total: 0, notes: "", checked: false },
  { name: "watermelon", type: "fruit", total: 0, notes: "", checked: false },
  { name: "pineapple", type: "fruit", total: 0, notes: "", checked: false },
  {
    name: "asparagus",
    type: "vegetable",
    total: 0,
    notes: "",
    checked: false,
  },
  {
    name: "cauliflower",
    type: "vegetable",
    total: 0,
    notes: "",
    checked: false,
  },
  { name: "kale", type: "vegetable", total: 0, notes: "", checked: false },
  { name: "spinach", type: "vegetable", total: 0, notes: "", checked: false },
  { name: "ginger", type: "vegetable", total: 0, notes: "", checked: false },
  { name: "cheese", type: "dairy", total: 0, notes: "", checked: false },
  { name: "butter", type: "dairy", total: 0, notes: "", checked: false },
  { name: "yogurt", type: "dairy", total: 0, notes: "", checked: false },
  { name: "eggs", type: "dairy", total: 0, notes: "", checked: false },
  { name: "almond milk", type: "dairy", total: 0, notes: "", checked: false },
  { name: "bread", type: "grain", total: 0, notes: "", checked: false },
  { name: "bagels", type: "grain", total: 0, notes: "", checked: false },
  {
    name: "english muffin",
    type: "grain",
    total: 0,
    notes: "",
    checked: false,
  },
  { name: "pasta", type: "grain", total: 0, notes: "", checked: false },
  { name: "rice", type: "grain", total: 0, notes: "", checked: false },
  { name: "oatmeal", type: "grain", total: 0, notes: "", checked: false },
  { name: "cereal", type: "grain", total: 0, notes: "", checked: false },
  { name: "crackers", type: "snacks", total: 0, notes: "", checked: false },
  { name: "pretzels", type: "snacks", total: 0, notes: "", checked: false },
  {
    name: "granola bars",
    type: "snacks",
    total: 0,
    notes: "",
    checked: false,
  },
  { name: "popcorn", type: "snacks", total: 0, notes: "", checked: false },
  {
    name: "dried fruits",
    type: "snacks",
    total: 0,
    notes: "",
    checked: false,
  },
  { name: "chips", type: "snacks", total: 0, notes: "", checked: false },
  { name: "chocolate", type: "sweets", total: 0, notes: "", checked: false },
  {
    name: "jelly beans",
    type: "sweets",
    total: 0,
    notes: "",
    checked: false,
  },
  {
    name: "hershey's kisses",
    type: "sweets",
    total: 0,
    notes: "",
    checked: false,
  },
  { name: "ice cream", type: "sweets", total: 0, notes: "", checked: false },
  { name: "cake", type: "sweets", total: 0, notes: "", checked: false },
  { name: "cookies", type: "sweets", total: 0, notes: "", checked: false },
  { name: "pie", type: "sweets", total: 0, notes: "", checked: false },
  {
    name: "toothbrushes",
    type: "other",
    total: 0,
    notes: "",
    checked: false,
  },
  { name: "deodorant", type: "other", total: 0, notes: "", checked: false },
  { name: "batteries", type: "other", total: 0, notes: "", checked: false },
  {
    name: "paper towels",
    type: "other",
    total: 0,
    notes: "",
    checked: false,
  },
  {
    name: "toilet paper",
    type: "other",
    total: 0,
    notes: "",
    checked: false,
  },
  { name: "tylenol", type: "other", total: 0, notes: "", checked: false },
  {
    name: "peanut butter",
    type: "misc foods",
    total: 0,
    notes: "",
    checked: false,
  },
  { name: "nutmeg", type: "misc foods", total: 0, notes: "", checked: false },
  {
    name: "tumeric",
    type: "misc foods",
    total: 0,
    notes: "",
    checked: false,
  },
  {
    name: "coriandor",
    type: "misc foods",
    total: 0,
    notes: "",
    checked: false,
  },
  { name: "cumin", type: "misc foods", total: 0, notes: "", checked: false },
  { name: "salt", type: "misc foods", total: 0, notes: "", checked: false },
  { name: "pepper", type: "misc foods", total: 0, notes: "", checked: false },
  { name: "peas", type: "frozen", total: 0, notes: "", checked: false },
  { name: "pizza", type: "frozen", total: 0, notes: "", checked: false },
  {
    name: "mixed berries",
    type: "frozen",
    total: 0,
    notes: "",
    checked: false,
  },
];
